# Simulation settings for using moveit_sim_controllers
moveit_sim_hw_interface:
  joint_model_group: arm
  joint_model_group_pose: start
# Settings for ros_control_boilerplate control loop
generic_hw_control_loop:
  loop_hz: 300
  cycle_time_error_threshold: 0.01
# Settings for ros_control hardware interface
hardware_interface:
  joints:
    - shoulder_pan_joint
    - shoulder_lift_joint
    - elbow_joint
    - wrist_1_joint
    - wrist_2_joint
    - wrist_3_joint
    - finger1_joint
    - finger2_joint
  sim_control_mode: 1  # 0: position, 1: velocity
# Publish all joint states
# Creates the /joint_states topic necessary in ROS

# arm:
#   joint_state_controller:
#     type: joint_state_controller/JointStateController
#     publish_rate: 100
#   arm_controller:
#     type: par_computado/ParComputado
#     joints:
#     - shoulder_pan_joint
#     - shoulder_lift_joint
#     - elbow_joint
#     - wrist_1_joint
#     - wrist_2_joint
#     - wrist_3_joint
#   gripper_controller:
#     type: effort_controllers/JointTrajectoryController
#     joints:
#     - finger1_joint
#     - finger2_joint
#     gains:
#       finger1_joint:
#         p: 1
#         d: 0
#         i: 0
#         i_clamp: 1
#       finger2_joint:
#         p: 1
#         d: 0
#         i: 0
#         i_clamp: 1


joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100
arm_controller:
  type: par_computado/ParComputado
  joints:
  - elbow_joint
  - shoulder_lift_joint
  - shoulder_pan_joint
  - wrist_1_joint
  - wrist_2_joint
  - wrist_3_joint
gripper_controller:
  type: effort_controllers/JointTrajectoryController
  joints:
  - finger1_joint
  - finger2_joint
  gains:
    finger1_joint:
      p: 1
      d: 0
      i: 0
      i_clamp: 1
    finger2_joint:
      p: 1
      d: 0
      i: 0
      i_clamp: 1

# initial:  # Define initial robot poses.
#   - group: arm
#     pose: guidance
#   - group: gripper
#     pose: gripper_open

# joint_state_controller:
#   type: joint_state_controller/JointStateController
#   publish_rate: 50

  #     arm_controller:
  # type: effort_controllers/JointTrajectoryController
  # joints:
  #   - shoulder_pan_joint
  #   - shoulder_lift_joint
  #   - elbow_joint
  #   - wrist_1_joint
  #   - wrist_2_joint
  #   - wrist_3_joint
  # gains:
  #   shoulder_pan_joint:
  #     p: 5000
  #     d: 0
  #     i: 1
  #     i_clamp: 1
  #   shoulder_lift_joint:
  #     p: 5000
  #     d: 0
  #     i: 1
  #     i_clamp: 1
  #   elbow_joint:
  #     p: 100
  #     d: 0
  #     i: 1
  #     i_clamp: 1
  #   wrist_1_joint:
  #     p: 100
  #     d: 0
  #     i: 1
  #     i_clamp: 1
  #   wrist_2_joint:
  #     p: 100
  #     d: 0
  #     i: 1
  #     i_clamp: 1
  #   wrist_3_joint:
  #     p: 100
  #     d: 0
  #     i: 1
  #     i_clamp: 1

# gripper_controller:
#   type: effort_controllers/JointTrajectoryController
#   joints:
#   - finger1_joint
#   - finger2_joint
#   gains:
#     finger1_joint:
#       p: 1
#       d: 0
#       i: 0
#       i_clamp: 1
#     finger2_joint:
#       p: 1
#       d: 0
#       i: 0
#       i_clamp: 1


# controller_manager_ns: /arm
controller_list:
  - name: arm_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - shoulder_pan_joint
      - shoulder_lift_joint
      - elbow_joint
      - wrist_1_joint
      - wrist_2_joint
      - wrist_3_joint
  - name: gripper_controller
    action_ns: follow_joint_trajectory
    default: True
    type: FollowJointTrajectory
    joints:
      - finger1_joint
      - finger2_joint